<?php

namespace Database\Seeders;

use App\Models\CoffeeBean;
use Illuminate\Database\Seeder;

class MasterSeeder extends Seeder
{
    public function run()
    {
        CoffeeBean::insert([
            [
                'coffee_no' => '5',
                'product_name' => 'スマトラ　ガヨ　コピ・ルアック　ワイルド',
                'grams' => '100',
                'price' => '4000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '6',
                'product_name' => 'パナマ　エスメラルダ　ゲイシャ',
                'grams' => '100',
                'price' => '4000',
                'roast' => '3',
            ],
            [
                'coffee_no' => '1',
                'product_name' => 'ジャマイカ　グライスデール農園　ブルーマウンテンNo.1',
                'grams' => '90',
                'price' => '3000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '2',
                'product_name' => 'イエメン モカ ガリブ ファーマーズロット',
                'grams' => '90',
                'price' => '3000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '8',
                'product_name' => 'ハワイ　コナ　エクストラファンシー',
                'grams' => '90',
                'price' => '3000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '9',
                'product_name' => 'ブラジル　ラウリーナ　ブルボン　リロイ',
                'grams' => '120',
                'price' => '3000',
                'roast' => '3',
            ],
            [
                'coffee_no' => '10',
                'product_name' => 'インドネシア　馬面マンデリン',
                'grams' => '120',
                'price' => '2000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '4',
                'product_name' => 'ガテマラ　アンティグア　ブエナビスタ農園　ゲイシャ',
                'grams' => '120',
                'price' => '2000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '12',
                'product_name' => 'タイ　ドイバンコン　ナチュラル',
                'grams' => '160',
                'price' => '2000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '14',
                'product_name' => 'ブラジル　セルトン農園　樹齢百年　レッドブルボン',
                'grams' => '160',
                'price' => '2000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '15',
                'product_name' => 'イエメン　モカ　マタリトラディショナル',
                'grams' => '90',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '16',
                'product_name' => 'ケニア　マサイ　AA',
                'grams' => '90',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '19',
                'product_name' => 'コロムビア　ら　フォルトゥナ農園　TABI',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '20',
                'product_name' => 'ニカラグア　ジャバニカ　マイクロロット',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '21',
                'product_name' => 'インドネシア　モジャンガルト農園　ウエストジャバ',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '22',
                'product_name' => 'ラオス　ボラベンティピカ',
                'grams' => '100',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '51',
                'product_name' => 'エチオピア　グジ　ゲイシャ　G3',
                'grams' => '100',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '23',
                'product_name' => 'ミャンマー　シャンリー',
                'grams' => '120',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '13',
                'product_name' => 'ブラジル Static Box Natural ハンショグランジ農園',
                'grams' => '120',
                'price' => '1000',
                'roast' => '3',
            ],
            [
                'coffee_no' => '24',
                'product_name' => 'エチオピア　イルガチャフィ　G1　ナチュラル',
                'grams' => '120',
                'price' => '1000',
                'roast' => '3',
            ],
            [
                'coffee_no' => '25',
                'product_name' => 'イエメン　モカマタリ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '26',
                'product_name' => 'インド　モンスーン',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '27',
                'product_name' => 'インドネシア　フローレス島　コモドドラゴン',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '28',
                'product_name' => 'インドネシア　アチェ　ガヨ　アラビカ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '31',
                'product_name' => 'マンデリン ベイビーシナール ピーベリー',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '32',
                'product_name' => 'エクアドル　JASオーガニック　アンデスマウンテン',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '33',
                'product_name' => 'ニカラグア　マラゴジッペ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '34',
                'product_name' => 'ドミニカ　バラオナAA',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '36',
                'product_name' => 'ガテマラ　ジェヌイン　アンティグア　ラ・アゾテア',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '37',
                'product_name' => 'キューバ　TL',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '38',
                'product_name' => 'コスタリカ　ジャガー　ハニー',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '39',
                'product_name' => 'コロムビア　KYOTO農園　JASオーガニック',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '40',
                'product_name' => 'コロムビア　カフェインレス　CO2処理',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '41',
                'product_name' => 'タンザニア　ん・ごろごろ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '42',
                'product_name' => 'タンザニア　テンボテンボ農園　ブラックエレファント',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '43',
                'product_name' => 'パプアニューギニア　キンデンAA　ピーベリー',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '44',
                'product_name' => '東ティモール　サンテモンテ　JASオーガニック',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '45',
                'product_name' => 'ブルンジ　ブルボン　AA',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '46',
                'product_name' => 'ペルー　マチュピチュ　　JASオーガニック',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '47',
                'product_name' => 'タンザニア　ハイツ農園　ピーベリー',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '48',
                'product_name' => 'ルワンダ　スカイヒル　ブルボン',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '49',
                'product_name' => 'メキシコ　ベラクルス',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '52',
                'product_name' => 'ボンジュラス　セレクトマウンテン　SHG',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '55',
                'product_name' => 'ウガンダ　ブルーナイル',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '56',
                'product_name' => 'エチオピア　モカシダモ　G2',
                'grams' => '200',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '58',
                'product_name' => 'ガテマラ　SHB',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '64',
                'product_name' => 'タンザニア　リマ農園　KIBO　AA　RA認証',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '63',
                'product_name' => 'タンザニア　ナチュラル　スウィートキリマンジェロ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '65',
                'product_name' => 'ブラジル　カフェドルチェ',
                'grams' => '200',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '66',
                'product_name' => 'ブラジル　サントス　ショコラ',
                'grams' => '200',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '67',
                'product_name' => 'ブラジル　ブラナウト農園　エスプレッソ　レディ',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '68',
                'product_name' => 'マンデリン　G1',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '70',
                'product_name' => 'コンゴ　ミノヴァ',
                'grams' => '200',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '73',
                'product_name' => 'エルサルバドル　HG',
                'grams' => '400',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '74',
                'product_name' => 'キリマンジェロAA',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '75',
                'product_name' => 'コロムビア　スプレモ',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '72',
                'product_name' => 'エチオピア　モカシダモ',
                'grams' => '400',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '76',
                'product_name' => 'ブラジル　サントス　No.2',
                'grams' => '400',
                'price' => '1000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '77',
                'product_name' => 'ベトナム　アラビカ　エバーグリーン　M18',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '78',
                'product_name' => 'ホンジュラス　HG',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '80',
                'product_name' => 'ブラジル さくらブルボン',
                'grams' => '250',
                'price' => '2000',
                'roast' => '4',
            ],
            [
                'coffee_no' => '33',
                'product_name' => 'ブラジル　サントス　ヴィオレッタ',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
            ],
            [
                'coffee_no' => '37-2',
                'product_name' => 'キューバ　TL',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
            ],
            [
                'coffee_no' => '69',
                'product_name' => 'ウガンダ　ルウェンゾリ　アフリカンスノードンキー',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
            ],
        ]);
    }

}
