<?php

namespace Database\Seeders;

use App\Models\Order;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    public function run()
    {
        Order::insert([
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/10/28',
                'receiving_date' => '2020/11/02',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
                'count' => 1
                ,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/10/28',
                'receiving_date' => '2020/11/02',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/10/28',
                'receiving_date' => '2020/11/25',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/10/28',
                'receiving_date' => '2020/11/30',
                'grams' => '90',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/10/28',
                'receiving_date' => '2020/11/09',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/11/26',
                'receiving_date' => '2020/12/16',
                'grams' => '90',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/11/26',
                'receiving_date' => '2020/12/21',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/11/26',
                'receiving_date' => '2020/12/07',
                'grams' => '160',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/11/26',
                'receiving_date' => '2020/12/16',
                'grams' => '120',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/12/16',
                'receiving_date' => '2021/01/04',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/12/16',
                'receiving_date' => '2021/01/18',
                'grams' => '100',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/12/16',
                'receiving_date' => '2021/01/10',
                'grams' => '120',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2020/12/16',
                'receiving_date' => '2021/01/18',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/01/18',
                'receiving_date' => '2020/02/17',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/01/18',
                'receiving_date' => '2021/02/03',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/01/18',
                'receiving_date' => '2021/02/08',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/01/18',
                'receiving_date' => '2021/02/08',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/01/18',
                'receiving_date' => '2020/02/17',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/02/25',
                'receiving_date' => '2021/03/04',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/02/25',
                'receiving_date' => '2021/03/18',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/02/25',
                'receiving_date' => '2021/03/29',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/02/25',
                'receiving_date' => '2021/03/04',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/02/25',
                'receiving_date' => '2021/03/18',
                'grams' => '120',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/03/30',
                'receiving_date' => '2021/04/05',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/03/30',
                'receiving_date' => '2021/04/05',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/03/30',
                'receiving_date' => '2021/04/12',
                'grams' => '250',
                'price' => '2000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/03/30',
                'receiving_date' => '2021/04/05',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/04/21',
                'receiving_date' => '2021/05/26',
                'grams' => '160',
                'price' => '2000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/04/21',
                'receiving_date' => '2021/05/31',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/04/21',
                'receiving_date' => '2021/05/06',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/04/21',
                'receiving_date' => '2021/05/26',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/05/26',
                'receiving_date' => '2021/06/11',
                'grams' => '160',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/05/26',
                'receiving_date' => '2021/06/07',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/05/26',
                'receiving_date' => '2021/06/11',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/05/26',
                'receiving_date' => '2021/06/11',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/06/28',
                'receiving_date' => '2021/07/05',
                'grams' => '150',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/06/28',
                'receiving_date' => '2021/07/05',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/06/28',
                'receiving_date' => '2021/07/19',
                'grams' => '90',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/06/28',
                'receiving_date' => '2021/07/19',
                'grams' => '120',
                'price' => '2000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/07/28',
                'receiving_date' => '2021/08/01',
                'grams' => '100',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/07/28',
                'receiving_date' => '2021/08/01',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/07/28',
                'receiving_date' => '2021/08/16',
                'grams' => '120',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/07/28',
                'receiving_date' => '2021/08/16',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/07/28',
                'receiving_date' => '2021/08/16',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/08/30',
                'receiving_date' => '2021/09/06',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/08/30',
                'receiving_date' => '2021/09/06',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/08/30',
                'receiving_date' => '2021/09/27',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/08/30',
                'receiving_date' => '2021/09/27',
                'grams' => '400',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/08/30',
                'receiving_date' => '2021/09/27',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/09/29',
                'receiving_date' => '2021/10/11',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/09/29',
                'receiving_date' => '2021/10/11',
                'grams' => '160',
                'price' => '2000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/09/29',
                'receiving_date' => '2021/10/25',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/09/29',
                'receiving_date' => '2021/10/25',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/10/27',
                'receiving_date' => '2021/11/01',
                'grams' => '160',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/10/27',
                'receiving_date' => '2021/11/01',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/10/27',
                'receiving_date' => '2021/11/15',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/10/27',
                'receiving_date' => '2021/11/15',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/11/29',
                'receiving_date' => '2021/12/06',
                'grams' => '200',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/11/29',
                'receiving_date' => '2021/12/06',
                'grams' => '120',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/11/29',
                'receiving_date' => '2021/12/13',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2021/11/29',
                'receiving_date' => '2021/12/13',
                'grams' => '150',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/04',
                'receiving_date' => '2022/01/17',
                'grams' => '400',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/04',
                'receiving_date' => '2022/01/17',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/04',
                'receiving_date' => '2022/01/31',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/04',
                'receiving_date' => '2022/01/31',
                'grams' => '160',
                'price' => '2000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/31',
                'receiving_date' => '2022/02/14',
                'grams' => '120',
                'price' => '1000',
                'roast' => '4',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/31',
                'receiving_date' => '2022/02/14',
                'grams' => '150',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/31',
                'receiving_date' => '2022/02/14',
                'grams' => '200',
                'price' => '1000',
                'roast' => '6',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/31',
                'receiving_date' => '2022/02/28',
                'grams' => '400',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
            [
                'coffee_bean_id' => '0',
                'purchase_order_date' => '2022/01/31',
                'receiving_date' => '2022/02/28',
                'grams' => '100',
                'price' => '1000',
                'roast' => '5',
                'count' => 1,
            ],
        ]);
    }
}
