name: create-pull-request-develop-to-master

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  createdPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Pull Request Action for master
        uses: repo-sync/pull-request@v2.5
        with:
          source_branch: "develop"
          destination_branch: "master"
          pr_title: "$(date +%Y-%m-%d) Release"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}